language: android
sudo: required
dist: precise

android:
  components:
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository,
    - extra-android-support
    - extra-google-gcm
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-intel-Hardware_Accelerated_Execution_Manager
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'
    - 'mips-android-sysimage-license-.+'

jdk:
  - oraclejdk8

before_install:
  - export FIREBASE_TEST_LAB_KEY_FILE=$HOME/travis-service-account.json
  - export FIREBASE_TEST_LAB_KEY_FILE_AVAILABLE=false
  - openssl aes-256-cbc -K $encrypted_2eb1bd50e5de_key -iv $encrypted_2eb1bd50e5de_iv
    -in video-app-service-gcloud-service-account.json.enc -out $FIREBASE_TEST_LAB_KEY_FILE -d &&
    export FIREBASE_TEST_LAB_KEY_FILE_AVAILABLE=true || true

before_script:
   #######################################
   #
   # Gradle
   #
   ######################################

   #######################################
   #
   # Android SDK
   #
   ######################################
   - mkdir "$ANDROID_HOME/licenses" || true
   - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
   # Ensure all dependencies are installed before building
   - ./gradlew dependencies || true

   #######################################
   #
   # Google Cloud SDK
   #
   ######################################
   - pushd ~
   - wget -q https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-138.0.0-linux-x86_64.tar.gz
   - tar xzf google-cloud-sdk-138.0.0-linux-x86_64.tar.gz
   - ./google-cloud-sdk/install.sh --usage-reporting=true --path-update=false --bash-completion=false --additional-components alpha beta gcloud
   - rm -rf google-cloud-sdk-138.0.0-linux-x86_64.tar.gz
   - ./google-cloud-sdk/bin/gcloud config set --installation component_manager/disable_update_check true
   - export GCLOUD_SDK_HOME="$HOME/google-cloud-sdk"
   - export PATH="$HOME/google-cloud-sdk/bin:$PATH"
   - 'if [ "FIREBASE_TEST_LAB_KEY_FILE_AVAILABLE" != "false" ]; then gcloud auth activate-service-account --key-file=$FIREBASE_TEST_LAB_KEY_FILE; fi'
   - popd

   #######################################
   #
   # Android NDK Setup
   #
   ######################################
   - pushd ~
   - wget -q https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
   - unzip -qo android-ndk-r12b-linux-x86_64.zip
   - export ANDROID_NDK_HOME="$HOME/android-ndk-r12b"
   - popd

    #######################################
    #
    # Android Emulator Setup
    #
    ######################################
   # Create and start an emulator for instrumentation tests.
   - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
   - emulator -avd test -no-window &
   - android-wait-for-emulator
   - adb shell input keyevent 82

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
  - 'if [ "FIREBASE_TEST_LAB_KEY_FILE_AVAILABLE" != "false" ]; then gcloud beta test android devices list; fi'
  - ./gradlew clean -PtestCoverageEnabled=true library:jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
