language: android
sudo: required
dist: precise

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'

jdk:
  - oraclejdk8

stages:
  - name: test
    if: type IN (push, pull_request) AND tag is blank
  - name: snapshot
    if: type = push AND branch IN (master, 2.0)
  - name: release candidate
    if: tag =~ ^\d+\.\d+\.\d+-rc\d+$

before_install:
  - export FIREBASE_TEST_LAB_KEY_FILE=$HOME/travis-service-account.json
  - export FIREBASE_TEST_LAB_KEY_FILE_AVAILABLE=false
  - openssl aes-256-cbc -K $encrypted_2eb1bd50e5de_key -iv $encrypted_2eb1bd50e5de_iv
    -in video-app-service-gcloud-service-account.json.enc -out $FIREBASE_TEST_LAB_KEY_FILE -d &&
    export FIREBASE_TEST_LAB_KEY_FILE_AVAILABLE=true || true

before_script:
   # git
   - git config --global user.email "travis@travis-ci.org"
   - git config --global user.name "Travis CI"

   # cmake
   - wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
   - chmod +x install-cmake.sh
   - ./install-cmake.sh > /dev/null

   # Google Cloud SDK
   - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
   - source /home/travis/google-cloud-sdk/path.bash.inc
   - gcloud version

   # Android NDK Setup
   - pushd ~
   - wget -q https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
   - unzip -qo android-ndk-r12b-linux-x86_64.zip
   - export ANDROID_NDK_HOME="$HOME/android-ndk-r12b"
   - popd

cache:
  directories:
    - $HOME/.gradle
    - $HOME/google-cloud-sdk

jobs:
  include:
    - stage: test
      script: echo "test"
    - stage: snapshot
      script: echo "snapshot"
    - stage: release candidate
      script: ./gradlew incrementRc
